#
# reference:
#   - https://lukasgeiter.github.io/mkdocs-awesome-nav/reference/
#

# preserve_directory_names: true
# flatten_single_child_sections: true # TODO X: 配合排序插件, 必备参数!!!

nav:
  - 概述: index.md
  - "功能组件": component
  - "UI 组件": ui
  - "Admin 组件": admin
  - "*"
