version: "3"

#
# sub namespace: https://taskfile.dev/#/usage?id=including-other-taskfiles
#
includes:
  x:
    taskfile: .task/config/ # by rsync
    dir: .
    optional: true

vars:
  VAR1: "some-var"

# global env:
env:
  ENV1: testing

# env file:
dotenv:
  - .env

################################################################################################

tasks:
  default:
    cmds:
      - echo "hello world"

  ################################################################################

  uv:
    cmds:
      - uv {{.CLI_ARGS}}

  sync:
    aliases: ["i", "sc", "install"]
    cmds:
      - uv sync --all-packages --all-groups --upgrade

  docs:
    aliases: ["d"]
    cmds:
      - uv run mkdocs serve --open --watch=docs --watch=mkdocs.yml --dev-addr=localhost:5005
    # dir: "docs"

  # 编译+部署到 Github gh-pages
  docs:deploy:
    aliases: ["docs:d", "dd", "du", "doc:up"]
    cmds:
      - uv run mkdocs gh-deploy # build and create gh-pages branch
      - git push origin gh-pages:gh-pages --force # push to public repo
    # dir: "docs"
    ignore_error: true

  ################################################################################

  count:
    cmds:
      - tokei # 代码统计: https://github.com/XAMPPRocky/tokei

  quick:
    aliases: ["q"]
    cmds:
      - task: cc
      - task: push

  # usage: task rc -- 2
  rc:
    aliases: ["reset:commit"]
    cmds:
      - git reset --soft HEAD~{{.CLI_ARGS}}
      - task: c

  cc:
    cmds:
      - task: commit
      - task: commit

  commit:
    aliases: ["c"]
    cmds:
      - git add .
      - git status
      - git commit -m "update" --no-verify
    ignore_error: true

  pull:
    cmds:
      - git config pull.rebase false
      - git pull origin main

  push:
    cmds:
      - git push origin main --tags
      - repo_url=`git remote -v | grep push | awk -F ":" '{print $2}' | awk -F ".git" '{print "https://github.com/"$1}'`; open $repo_url
